<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		  <PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BuildingBlocks\BuildingBlocks.csproj" />
		<ProjectReference Include="..\SharedKernel\SharedKernel.csproj" />
		<ProjectReference Include="..\Hivify.AI\Hivify.AI.csproj" />
		<ProjectReference Include="..\ServiceDefaults1\ServiceDefaults.csproj" />

		<ProjectReference Include="..\src\Association\Application\Association.Application.csproj" />
		<ProjectReference Include="..\src\Association\Infrastructure\Association.Infrastructure.csproj" />

		<ProjectReference Include="..\src\Complaints\Application\Complaints.Application.csproj" />
		<ProjectReference Include="..\src\Complaints\Infrastructure\Complaints.Infrastructure.csproj" />

		<ProjectReference Include="..\src\DocumentsMgmt\DocumentsMgmt.Application\DocumentsMgmt.Application.csproj" />

		<ProjectReference Include="..\src\Feeds\Application\Feeds.Application.csproj" />
		<ProjectReference Include="..\src\Feeds\Infrastructure\Feeds.Infrastructure.csproj" />

		<ProjectReference Include="..\src\Houses\Application\Houses.Application.csproj" />
		<ProjectReference Include="..\src\Houses\Infrastructure\Houses.Infrastructure.csproj" />

		<ProjectReference Include="..\src\UserMgmt\UserMgmt.Application\UserMgmt.Application.csproj" />
		<ProjectReference Include="..\src\UserMgmt\UserMgmt.Infrastructure\UserMgmt.Infrastructure.csproj" />
	</ItemGroup>

</Project>